name: Python CI

# Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches: 
        - main
  pull_request:
    branches: 
        - main

# Define the jobs that will run in this workflow
jobs:
    test:
        runs-on: ubuntu-latest  # Use the latest Ubuntu runner

        steps:
            # STEP 1: Check out the code from the repository
            - name: Checkout code
              uses: actions/checkout@v2  # Checkout the repository code

            # STEP 2: Set up Python environment
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'  # Specify the Python version

            # STEP 3: Install dependencies and run tests
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt  # Install dependencies from requirements.txt

            # STEP 4: Run tests
            - name: Run tests
              run: pytest  # Run the tests using pytest
